language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "node"
cache:
  directories:
    - node_modules
script:
  - "npm run test"
  - "npm run lint"
  - "npm run test:ci"
before_script:
  - export TZ=America/Los_Angeles
